package gitlab

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"

	"github.com/alexandervidyaev/flux-tools/pkg/output"
)

// NewClient creates a new GitLab API client
func NewClient(baseURL, token, projectID string, timeoutSeconds int) *Client {
	// Default timeout
	if timeoutSeconds <= 0 {
		timeoutSeconds = 30
	}

	return &Client{
		BaseURL:   baseURL,
		Token:     token,
		ProjectID: projectID,
		HTTPClient: &http.Client{
			Timeout: time.Duration(timeoutSeconds) * time.Second,
		},
	}
}

// ListMergeRequestNotes lists all notes (comments) for a merge request
func (c *Client) ListMergeRequestNotes(mrIID string) ([]Note, error) {
	base := fmt.Sprintf("%s/projects/%s/merge_requests/%s/notes",
		c.BaseURL, url.PathEscape(c.ProjectID), mrIID)

	// Follow GitLab pagination via X-Next-Page: a single ?per_page=100 request
	// silently dropped everything past the first page, so on busy MRs old
	// flux-tools comments beyond 100 notes were never deleted.
	var all []Note
	page := 1
	for {
		endpoint := fmt.Sprintf("%s?per_page=100&page=%d", base, page)

		req, err := http.NewRequest("GET", endpoint, nil)
		if err != nil {
			return nil, fmt.Errorf("failed to create request: %w", err)
		}

		req.Header.Set("PRIVATE-TOKEN", c.Token)
		req.Header.Set("Content-Type", "application/json")

		resp, err := c.HTTPClient.Do(req)
		if err != nil {
			return nil, fmt.Errorf("failed to execute request: %w", err)
		}

		if resp.StatusCode != http.StatusOK {
			body, _ := io.ReadAll(resp.Body)
			resp.Body.Close()
			return nil, fmt.Errorf("API error %d: %s", resp.StatusCode, string(body))
		}

		var notes []Note
		if err := json.NewDecoder(resp.Body).Decode(&notes); err != nil {
			resp.Body.Close()
			return nil, fmt.Errorf("failed to decode response: %w", err)
		}
		resp.Body.Close()
		all = append(all, notes...)

		next, err := strconv.Atoi(resp.Header.Get("X-Next-Page"))
		if err != nil || next <= page {
			// Empty or absent X-Next-Page — last page reached
			return all, nil
		}
		page = next
	}
}

// DeleteNote deletes a note (comment) from a merge request
func (c *Client) DeleteNote(mrIID string, noteID int) error {
	endpoint := fmt.Sprintf("%s/projects/%s/merge_requests/%s/notes/%d",
		c.BaseURL, url.PathEscape(c.ProjectID), mrIID, noteID)

	req, err := http.NewRequest("DELETE", endpoint, nil)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("PRIVATE-TOKEN", c.Token)

	client := c.HTTPClient
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusNoContent && resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("API error %d: %s", resp.StatusCode, string(body))
	}

	return nil
}

// PostNote posts a new note (comment) to a merge request with environment-specific marker
func (c *Client) PostNote(mrIID string, body string, environment string) error {
	endpoint := fmt.Sprintf("%s/projects/%s/merge_requests/%s/notes",
		c.BaseURL, url.PathEscape(c.ProjectID), mrIID)

	// Add environment-specific comment marker to identify flux-tools comments
	marker := GetCommentMarker(environment)
	markedBody := marker + "\n\n" + body

	payload := map[string]string{
		"body": markedBody,
	}

	jsonData, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("failed to marshal payload: %w", err)
	}

	req, err := http.NewRequest("POST", endpoint, bytes.NewBuffer(jsonData))
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("PRIVATE-TOKEN", c.Token)
	req.Header.Set("Content-Type", "application/json")

	client := c.HTTPClient
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusCreated && resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("API error %d: %s", resp.StatusCode, string(body))
	}

	return nil
}

// DeleteFluxToolsComments deletes comments generated by flux-tools for specific environment
// If environment is empty, deletes all flux-tools comments
// rateLimitMs: < 0 = use default (200ms), = 0 = no rate limiting, > 0 = use specified value
func (c *Client) DeleteFluxToolsComments(mrIID string, environment string, rateLimitMs int) (int, error) {
	// Default rate limit
	if rateLimitMs < 0 {
		rateLimitMs = 200
	}

	notes, err := c.ListMergeRequestNotes(mrIID)
	if err != nil {
		return 0, fmt.Errorf("failed to list notes: %w", err)
	}

	deleted := 0
	for _, note := range notes {
		// Skip system notes
		if note.System {
			continue
		}

		// Check if comment contains our marker for this environment
		if containsMarker(note.Body, environment) {
			if err := c.DeleteNote(mrIID, note.ID); err != nil {
				// Log error but continue with other notes
				pr := output.New(false)
				pr.Warn("Failed to delete note %d: %v\n", note.ID, err)
				continue
			}
			deleted++
			// Rate limiting (skip if rateLimitMs == 0)
			if rateLimitMs > 0 {
				time.Sleep(time.Duration(rateLimitMs) * time.Millisecond)
			}
		}
	}

	return deleted, nil
}

// containsMarker checks if a comment body contains the flux-tools marker for specific environment
// If environment is empty, checks for any flux-tools marker
func containsMarker(body string, environment string) bool {
	return strings.HasPrefix(body, GetCommentMarker(environment))
}
