package gitlab

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/alexandervidyaev/flux-tools/internal/diff"
	"github.com/alexandervidyaev/flux-tools/pkg/output"
	"github.com/alexandervidyaev/flux-tools/pkg/workerpool"
)

const (
	maxCommentSize = 60000 // GitLab limit is ~65KB, use 60KB to be safe
)

// errNoChanges signals that a cluster diff contains no changes and was skipped.
// A sentinel error is used instead of matching on error text so the caller can
// distinguish "skipped" from a real failure via errors.Is.
var errNoChanges = errors.New("no changes")

// postOutcome captures what happened while posting a single cluster diff that
// is not conveyed by the error alone.
type postOutcome struct {
	tooLarge bool // diff exceeded the size limit; a compact placeholder was posted
}

// PostDiffsToMR posts all diff files to a GitLab merge request
func PostDiffsToMR(ctx context.Context, opts PostCommentOptions) (*PostResult, error) {
	result := &PostResult{}
	p := output.New(false)

	// Validate options
	if err := validateOptions(&opts); err != nil {
		return result, err
	}

	// Create GitLab client with timeout
	client := NewClient(opts.GitLabURL, opts.Token, opts.ProjectID, opts.Timeout)

	// Delete old flux-tools comments for this environment first
	if !opts.SkipDelete {
		envLabel := opts.Environment
		if envLabel == "" || envLabel == "N/A" {
			envLabel = "all environments"
		} else {
			envLabel = "environment: " + envLabel
		}
		p.Info("🗑️  Deleting old flux-tools comments (%s)...\n", envLabel)
		deleted, err := client.DeleteFluxToolsComments(opts.MergeRequestIID, opts.Environment, opts.DeleteRateLimitMs)
		if err != nil {
			p.Warn("failed to delete old comments: %v\n", err)
		} else {
			result.Deleted = deleted
			p.Info("  ✅ Deleted %d old comments\n", deleted)
		}
		p.Info("\n")
	}

	// Post index.md as the first, summary comment (written by SaveDiffsToFiles).
	// Best-effort: a missing index (older artifacts) is not an error.
	if err := postSummaryIndex(client, opts, p); err != nil {
		p.Warn("failed to post summary comment: %v\n", err)
	}

	// Post individual cluster diffs
	p.Info("📦 Posting cluster diffs...\n")
	if err := postClusterDiffs(ctx, client, opts, result, p); err != nil {
		return result, err
	}

	return result, nil
}

// postSummaryIndex posts the index.md summary generated by the diff command
// as a single comment ahead of the per-cluster ones.
// Posting is skipped entirely when SkipSummary is set.
func postSummaryIndex(client *Client, opts PostCommentOptions, p *output.Printer) error {
	if opts.SkipSummary {
		p.Info("📋 Summary comment skipped (--skip-summary)\n")
		return nil
	}

	indexPath := filepath.Join(opts.DiffsDir, "index.md")
	content, err := os.ReadFile(indexPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil // older artifacts have no index.md
		}
		return err
	}

	p.Info("📋 Posting summary comment (index.md)...\n")
	environment := opts.Environment
	if environment == "" {
		environment = "N/A"
	}
	body := fmt.Sprintf("-- Diff summary for environment: **%s** --\n\n%s", environment, content)
	return client.PostNote(opts.MergeRequestIID, body, opts.Environment)
}

// validateOptions validates and fills in default values for options
func validateOptions(opts *PostCommentOptions) error {
	if opts.DiffsDir == "" {
		return fmt.Errorf("diffs directory is required")
	}

	if _, err := os.Stat(opts.DiffsDir); err != nil {
		return fmt.Errorf("diffs directory not found: %s", opts.DiffsDir)
	}

	if opts.ProjectID == "" {
		return fmt.Errorf("project ID is required (set CI_PROJECT_ID or use --project-id)")
	}

	if opts.MergeRequestIID == "" {
		return fmt.Errorf("merge request IID is required (set CI_MERGE_REQUEST_IID or use --mr-iid)")
	}

	if opts.Token == "" {
		return fmt.Errorf("GitLab token is required (set GITLAB_TOKEN or use --token)")
	}

	if opts.GitLabURL == "" {
		opts.GitLabURL = "https://gitlab.com/api/v4"
	}

	return nil
}

// postClusterDiffs posts individual cluster diff files in parallel
func postClusterDiffs(ctx context.Context, client *Client, opts PostCommentOptions, result *PostResult, p *output.Printer) error {
	// Find all diff files
	pattern := filepath.Join(opts.DiffsDir, "*-diff.md")
	diffFiles, err := filepath.Glob(pattern)
	if err != nil {
		return fmt.Errorf("failed to find diff files: %w", err)
	}

	if len(diffFiles) == 0 {
		p.Warn("No cluster diff files found\n")
		return nil
	}

	// Sort for consistent order
	sort.Strings(diffFiles)

	// Determine number of workers
	workers := opts.Workers
	if workers <= 0 {
		workers = 3 // Default
	}
	if workers > len(diffFiles) {
		workers = len(diffFiles)
	}

	p.Info("  Using %d parallel workers\n", workers)

	type job struct {
		index       int
		filePath    string
		clusterName string
	}

	jobs := make([]job, 0, len(diffFiles))
	for i, diffFile := range diffFiles {
		jobs = append(jobs, job{
			index:       i,
			filePath:    diffFile,
			clusterName: strings.TrimSuffix(filepath.Base(diffFile), "-diff.md"),
		})
	}

	// Rate limiter with configurable delay
	// < 0 = use default (500ms)
	// = 0 = no rate limiting
	// > 0 = use specified value
	rateLimitMs := opts.RateLimitMs
	if rateLimitMs < 0 {
		rateLimitMs = 500 // Default
	}

	var rateLimiter *time.Ticker
	if rateLimitMs > 0 {
		rateLimiter = time.NewTicker(time.Duration(rateLimitMs) * time.Millisecond)
		defer rateLimiter.Stop()
	}

	// jobResult is the classified outcome of a single posted diff; counters are
	// aggregated after the pool finishes, so workers share no counter state.
	type jobResult struct {
		skipped  bool
		tooLarge bool
		err      error
	}

	// Progress lines are serialized so concurrent workers do not interleave them
	var printMu sync.Mutex

	for _, r := range workerpool.Run(ctx, jobs, workers, func(_ context.Context, j job) jobResult {
		// Wait for rate limiter if enabled
		if rateLimiter != nil {
			<-rateLimiter.C
		}

		outcome, err := postClusterDiff(client, opts, j.filePath, j.clusterName)

		printMu.Lock()
		defer printMu.Unlock()
		switch {
		case errors.Is(err, errNoChanges):
			p.Info("  [%d/%d] %s - ⏭️  Skipped (no changes)\n",
				j.index+1, len(diffFiles), j.clusterName)
			return jobResult{skipped: true}
		case err != nil:
			p.Info("  [%d/%d] %s - ❌ Error: %v\n",
				j.index+1, len(diffFiles), j.clusterName, err)
			return jobResult{err: err}
		default:
			p.Info("  [%d/%d] %s - ✅ Posted\n",
				j.index+1, len(diffFiles), j.clusterName)
			return jobResult{tooLarge: outcome.tooLarge}
		}
	}) {
		switch {
		case r.skipped:
			result.Skipped++
		case r.err != nil:
			result.Failed++
			result.Errors = append(result.Errors, r.err)
		default:
			result.Posted++
			if r.tooLarge {
				result.TooLarge++
			}
		}
	}

	return nil
}

// postClusterDiff posts a single cluster diff file. It returns errNoChanges
// (wrapped) when the cluster has no changes, so the caller can classify the
// outcome via errors.Is. The postOutcome reports whether a compact placeholder
// was posted because the diff exceeded the size limit.
func postClusterDiff(client *Client, opts PostCommentOptions, filePath, clusterName string) (postOutcome, error) {
	var outcome postOutcome

	content, err := os.ReadFile(filePath)
	if err != nil {
		return outcome, fmt.Errorf("failed to read file: %w", err)
	}

	body := string(content)

	// Check if there are no changes
	if strings.Contains(body, "## ✅ No changes") {
		return outcome, errNoChanges
	}

	// Get environment from options or use cluster name
	environment := opts.Environment
	if environment == "" {
		environment = "N/A"
	}

	// The structured JSON artifact is written next to the markdown file by
	// `flux-tools diff` (same image, same CI job) and is the only source of
	// stats and the compact format — the markdown reverse-parser is gone.
	clusterDiff, err := loadClusterDiffJSON(filePath)
	if err != nil {
		return outcome, fmt.Errorf("missing structured diff artifact (produced by an older flux-tools?): %w", err)
	}

	stats := calculateStatsFromChanges(clusterDiff.Changes)

	// Wrap entire content in collapsible details with statistics
	wrappedBody := fmt.Sprintf(`-- Diff for environment: **%s** cluster: **%s** --

➕ Added: %d   ➖ Deleted: %d   ⚙️ Modified: %d

<details>
<summary>Click to see details</summary>

%s

</details>
`, environment, clusterName, stats.Added, stats.Deleted, stats.Modified, body)

	// Check size (after wrapping)
	if len(wrappedBody) > maxCommentSize {
		// Use compact diff format: lists for Added/Deleted, full details for Modified
		compactBody := createCompactDiffFromChanges(clusterDiff.Changes, len(body), clusterName, opts)
		wrappedBody = fmt.Sprintf(`-- Diff for environment: **%s** cluster: **%s** --

➕ Added: %d   ➖ Deleted: %d   ⚙️ Modified: %d

<details>
<summary>Click to see details</summary>

%s

</details>
`, environment, clusterName, stats.Added, stats.Deleted, stats.Modified, compactBody)

		outcome.tooLarge = true
	}

	// Post comment with environment marker
	if err := client.PostNote(opts.MergeRequestIID, wrappedBody, opts.Environment); err != nil {
		return outcome, fmt.Errorf("failed to post: %w", err)
	}

	return outcome, nil
}

// Stats represents change statistics
type Stats struct {
	Added    int
	Deleted  int
	Modified int
}

// loadClusterDiffJSON loads the structured <cluster>-diff.json written next to
// the markdown diff.
func loadClusterDiffJSON(mdPath string) (*diff.ClusterDiff, error) {
	return diff.LoadClusterDiffFile(strings.TrimSuffix(mdPath, ".md") + ".json")
}

// calculateStatsFromChanges counts change types directly on the structured
// diff — no markdown parsing involved.
func calculateStatsFromChanges(changes []*diff.FileChange) Stats {
	stats := Stats{}
	for _, change := range changes {
		switch change.Status {
		case diff.StatusAdded:
			stats.Added++
		case diff.StatusDeleted:
			stats.Deleted++
		case diff.StatusModified:
			stats.Modified++
		}
	}
	return stats
}

// createCompactDiffFromChanges creates a compact diff directly from FileChange data
// This replaces the markdown parsing logic with direct data access
func createCompactDiffFromChanges(changes []*diff.FileChange, size int, clusterName string, opts PostCommentOptions) string {
	var output strings.Builder

	output.WriteString(fmt.Sprintf("⚠️ Diff too large to display (%d bytes)\n", size))
	output.WriteString("The diff for this cluster exceeds GitLab's comment size limit.\n\n")

	// Add instructions to view full diff at the top
	output.WriteString("**How to view full diff:**\n")

	// If we have project path and job ID, create direct link to artifact
	if opts.ProjectPath != "" && opts.JobID != "" {
		// Extract base URL from GitLabURL (remove /api/v4 if present)
		baseURL := strings.TrimSuffix(opts.GitLabURL, "/api/v4")
		artifactURL := fmt.Sprintf("%s/%s/-/jobs/%s/artifacts/raw/manifests-diffs/%s-diff.md",
			baseURL, opts.ProjectPath, opts.JobID, clusterName)
		output.WriteString(fmt.Sprintf("[**Download from artifacts**](%s)\n\n", artifactURL))
	} else {
		output.WriteString("Download the pipeline artifacts and open:\n")
		output.WriteString(fmt.Sprintf("`manifests-diffs/%s-diff.md`\n\n", clusterName))
	}

	output.WriteString("---\n\n")

	// Separate changes by type
	var addedResources []string
	var deletedResources []string
	var modifiedChanges []*diff.FileChange

	for _, change := range changes {
		resourceName := formatResourceName(change.Resource)

		switch change.Status {
		case diff.StatusAdded:
			addedResources = append(addedResources, resourceName)
		case diff.StatusDeleted:
			deletedResources = append(deletedResources, resourceName)
		case diff.StatusModified:
			modifiedChanges = append(modifiedChanges, change)
		}
	}

	// Sort lists alphabetically
	sort.Strings(addedResources)
	sort.Strings(deletedResources)

	// Build output - Added section
	if len(addedResources) > 0 {
		output.WriteString(fmt.Sprintf("### ➕ Added (%d):\n", len(addedResources)))
		for _, res := range addedResources {
			output.WriteString(fmt.Sprintf("- `%s`\n", res))
		}
		output.WriteString("\n")
	}

	// Deleted section
	if len(deletedResources) > 0 {
		output.WriteString(fmt.Sprintf("### ➖ Deleted (%d):\n", len(deletedResources)))
		for _, res := range deletedResources {
			output.WriteString(fmt.Sprintf("- `%s`\n", res))
		}
		output.WriteString("\n")
	}

	// Modified section - show full details
	if len(modifiedChanges) > 0 {
		output.WriteString(fmt.Sprintf("### ⚙️ Modified (%d):\n\n", len(modifiedChanges)))
		for i, change := range modifiedChanges {
			// Format resource header
			ns := change.Resource.Namespace
			if ns == "" {
				ns = "(none)"
			}

			output.WriteString(fmt.Sprintf("#### %d. Namespace:%s | Kind:%s | Name:%s\n\n",
				i+1, ns, change.Resource.Kind, change.Resource.Name))

			// Format diff block. CleanDiffLines strips git headers — present
			// when Changes came from the JSON artifact (raw git diff), absent
			// when they came from markdown reverse-parsing; cleaning is
			// idempotent for the latter.
			output.WriteString("```diff\n")
			for _, line := range diff.CleanDiffLines(change.Diff) {
				output.WriteString(line + "\n")
			}
			output.WriteString("```\n")

			if i < len(modifiedChanges)-1 {
				output.WriteString("\n")
			}
		}
	}

	return output.String()
}

// formatResourceName formats resource as namespace/kind/name or kind/name
func formatResourceName(resource diff.ResourceInfo) string {
	if resource.Namespace == "" {
		return fmt.Sprintf("%s/%s", resource.Kind, resource.Name)
	}
	return fmt.Sprintf("%s/%s/%s", resource.Namespace, resource.Kind, resource.Name)
}
